### ISSUE TITLE
First try with docker on Mac..

### ISSUE THREAD

**Issue by julfou81** [CAIsr/qsm#12]
Hi I just tried the docker tool on my mac on the test data provided with the python code and got the following output:

root@8bd479b57fd0:/data# tgv_qsm  -p epi3d_test_phase.nii.gz -m epi3d_test_mask.nii.gz -f 2.89 -t 0.027 -o epi3d_test_QSM
 >>>>  TGV-QSM  <<<<< 
-----------------------------------------
loading files...
  phase: epi3d_test_phase.nii.gz
  mask:  epi3d_test_mask.nii.gz
  output: epi3d_test_phaseepi3d_test_QSM_{number:03d}.nii.gz
Resampling phase data...
/usr/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:430: UserWarning: The behaviour of affine_transform with a one-dimensional array supplied for the matrix parameter has changed in scipy 0.18.0.
  "The behaviour of affine_transform with a one-dimensional "
Resampling magnitude/mask data...
Data looks good!
Processing initial laplacian of epi3d_test_phase.nii.gz ...
Processing QSM epi3d_test_phase.nii.gz ...
Factor 1.0 (1 of 1) - alpha = (0.0015, 0.0005)
  Iterations: 1000 (1 of 1)
Progress: [                         ]   0.0% Illegal instruction
root@8bd479b57fd0:/data# 

Do yo have any insights on what could be wrong?

Thank you again for sharing this useful tool!

**Comment by christiantinauer** [comment]
I have the same problem with Docker on Arch Linux.

**Comment by jdkent** [comment]
A quick  note: I think you may need to build the docker image locally if you haven't. if you pulled the image from dockerhub, I'm guessing the error is because your machines have an intel processor as opposed to an AMD processor. I built the image locally (modifying the [build_tgvqsm_.sh](https://github.com/CAIsr/qsm/blob/6c04e7506d3e2e7877b319934035233744715b88/build_tgvqsm_.sh) script), and I was able to get around the error.

**Comment by jdkent** [comment]
here is my [quickly hacked docker file creator script](https://github.com/jdkent/qsm/blob/b96ee8ecab53b96541df524f0befdab494f4c434/build_tgvqsm_fsl.sh), but you still need to build the image locally.

**Comment by stebo85** [comment]
Sorry, I completely missed this issue and just saw it. 

If this error comes up it means that the image was built on a CPU incompatible to the one your are running it on now. I haven't found a good workaround yet, except building the image again on this CPU type. 

I hope it works for you now.

all the best and sorry for the late reply
Steffen
