### ISSUE TITLE
qsm versus QSMxT 

### ISSUE THREAD

**Issue by jhuguetn** [CAIsr/qsm#14]
I wonder what are -in a nutshell- the similarities/differences between this pipeline and the [QSMxT](https://github.com/QSMxT/QSMxT) one? Is one an evolution of the other and therefore recommended to be used generally or simply tackle different goals/use-cases?   

thanks!

**Comment by stebo85** [comment]
Dear @jhuguetn,

this qsm pipeline here is a container that provides the tgv QSM algorithm. QSMxT provides many great features around tgv QSM: Dicom read-in and conversion; smart masking and dealing with multiecho data, template building (atlassing), image segementation. QSMxT will also offer machine learning based QSM techniques in the future.

I hope this helps for clarification :) Let us know if you have any other questions!

Cheers
Steffen

**Comment by jhuguetn** [comment]
Thanks @stebo85 for the quick and accurate response. It's clear now.

Regards,
Jordi
