### ISSUE TITLE
multi echo 

### ISSUE THREAD

**Issue by marinagrprat** [CAIsr/qsm#15]
Hi, I was wondering if the qsm pipleine can deal with multiecho data? I have tried to use the QSMxT for multiecho data but then I also need the T1w and T2*w right?

**Comment by stebo85** [comment]
Dear @marinagrprat,

QSMxT supports multiecho data out of the box and it combines the echoes automatically. What error did you get when you ran it? You don't need T1W data at all if you don't want anatomical segmentations that are based on T1w scan. T2W data is not required by the pipeline in any step - only gradient echo data.

Thank you
Steffen

**Comment by marinagrprat** [comment]
Hi Steffen! Thanks for the quick response! I was able to get the final QSM map!

Thank you,
Marina.

**Comment by stebo85** [comment]
wonderful to hear :)
